# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-symlinks
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: check-yaml
    - id: check-toml
    - id: check-json
    - id: check-ast
    - id: debug-statements
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-added-large-files
      args: [--maxkb=10000]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: '0.19.2'
    hooks:
    - id: check-github-workflows
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/ambv/black
    rev: '22.3.0'
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [pydantic==1.9.0,phantom-types==1.1.0]
  - repo: https://github.com/citation-file-format/cff-converter-python
    rev: "44e8fc9"
    hooks:
      - id: validate-cff
